CREATE DATABASE IF NOT EXISTS `penghitung_waktu`
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE `penghitung_waktu`;

DROP TABLE IF EXISTS `users`;

CREATE TABLE `users` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nama VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);